format = """$character$directory$git_branch"""
right_format = """$nodejs$hostname$localip$cmd_duration"""
add_newline = false

[directory]
truncation_length = 2
truncation_symbol = '../'

[os]
disabled = true
format = "$symbol"

[git_status]
disabled = false
style = "bold purple"

[hostname]
ssh_only = true
trim_at = ""
format = "[$ssh_symbol](bold blue) [$hostname](bold blue)"
disabled = false
ssh_symbol = ""

[localip]
ssh_only = true
format = "@(bold blue)[$localipv4](bold blue)"
disabled = false

[cmd_duration]
min_time = 1000
format = ' took [$duration](bold blue)'

[c]
symbol = " "

[docker_context]
symbol = " "

[git_branch]
symbol = " "

[golang]
symbol = " "

[lua]
symbol = " "

[memory_usage]
symbol = "󰍛 "

[nodejs]
symbol = " "
format = "via [ Node $version](bold green) "
detect_files = ["package.json", ".node-version"]
detect_folders = ["node_modules"]

[os.symbols]
Ubuntu = " "

[package]
symbol = "󰏗 "

[python]
symbol = " "

[rust]
symbol = " "
