add_newline = false

format = """$character$directory$git_status$git_branch"""

# move the rest of the prompt to the right
right_format = """$all"""

[os]
disabled = true
format = "$symbol"

[git_status]
disabled = false
style = "bold purple"

[hostname]
ssh_only = false
trim_at = "."
disabled = true
ssh_symbol = " "

[cmd_duration]
min_time = 500
format = 'took [$duration](bold yellow)'

[aws]
symbol = "  "

[c]
symbol = " "

[docker_context]
symbol = " "

[git_branch]
symbol = " "

[golang]
symbol = " "

[java]
symbol = " "

[lua]
symbol = " "

[memory_usage]
symbol = "󰍛 "

[nodejs]
symbol = " "
format = "via [ Node $version](bold green) "
detect_files = ["package.json", ".node-version"]
detect_folders = ["node_modules"]

[os.symbols]
Ubuntu = " "

[package]
symbol = "󰏗 "

[python]
symbol = " "

[rlang]
symbol = "󰟔 "

[ruby]
symbol = " "

[rust]
symbol = " "
