#!/usr/bin/env bash
# Generate every app's color file from the single palette (palette.sh).
# Run this after editing palette.sh, then reload the affected apps:
#   polybar:   ~/.config/polybar/launch.sh
#   i3:        i3-msg reload
#   tmux:      tmux source-file ~/.config/tmux/tmux.conf   (or restart)
#   alacritty: auto (live_config_reload)
#   nvim:      restart
set -euo pipefail

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$DIR/palette.sh"

CFG="$HOME/.config"
GEN="AUTO-GENERATED by ~/.config/theme/build.sh — edit palette.sh, not this file."
GEN_INI="; $GEN"
GEN_HASH="# $GEN"

# ----------------------------------------------------------------- polybar ---
cat > "$CFG/polybar/colors.ini" <<EOF
$GEN_INI
[colors]
base     = #$BG
mantle   = #$BG_DARK
crust    = #$BG_DEEP
text     = #$FG
subtext  = #$SUBTEXT
blue     = #$BLUE
lavender = #$PURPLE
sapphire = #$CYAN
sky      = #$CYAN
green    = #$GREEN
yellow   = #$YELLOW
peach    = #$ORANGE
red      = #$RED
mauve    = #$PURPLE
pink     = #$PINK
surface0 = #$SURFACE
surface1 = #$OVERLAY
surface2 = #$MUTED
overlay  = #$SURFACE
barbg    = #cc$SURFACE
EOF
echo "wrote polybar/colors.ini"

# --------------------------------------------------------------- alacritty ---
cat > "$CFG/alacritty/colors.toml" <<EOF
# $GEN
[colors.primary]
background        = "#$BG"
foreground        = "#$FG"
dim_foreground    = "#$MUTED"
bright_foreground = "#$FG"

[colors.cursor]
text   = "#$BG"
cursor = "#$PINK"

[colors.vi_mode_cursor]
text   = "#$BG"
cursor = "#$PURPLE"

[colors.selection]
text       = "#$BG"
background  = "#$PURPLE"

[colors.normal]
black   = "#$OVERLAY"
red     = "#$RED"
green   = "#$GREEN"
yellow  = "#$YELLOW"
blue    = "#$BLUE"
magenta = "#$PURPLE"
cyan    = "#$CYAN"
white   = "#$SUBTEXT"

[colors.bright]
black   = "#$MUTED"
red     = "#$RED"
green   = "#$GREEN"
yellow  = "#$YELLOW"
blue    = "#$BLUE"
magenta = "#$PINK"
cyan    = "#$CYAN"
white   = "#$FG"
EOF
echo "wrote alacritty/colors.toml"

# -------------------------------------------------------------------- rofi ---
cat > "$CFG/rofi/colors.rasi" <<EOF
/* $GEN */
* {
    bg:      #$BG;
    bg-alt:  #$SURFACE;
    fg:      #$FG;
    accent:  #$PURPLE;
    accent2: #$PINK;
    urgent:  #$RED;
    muted:   #$MUTED;
}
EOF
echo "wrote rofi/colors.rasi"

# ---------------------------------------------------------------------- i3 ---
cat > "$CFG/i3/colors.conf" <<EOF
$GEN_HASH
set \$base    #$BG
set \$surface #$SURFACE
set \$overlay #$OVERLAY
set \$text    #$FG
set \$muted   #$MUTED
set \$accent  #$PURPLE
set \$accent2 #$PINK
set \$urgent  #$RED
# i3lock wants a bare hex (no #)
set \$lockcolor $BG

# class                 border    backgr.   text     indicator  child_border
# Only the focused window is highlighted (accent); others get a muted border.
client.focused          \$accent   \$accent   \$base    \$accent2   \$accent
client.focused_inactive \$overlay  \$overlay  \$text    \$overlay   \$overlay
client.unfocused        \$overlay  \$overlay  \$muted   \$overlay   \$overlay
client.urgent           \$urgent   \$urgent   \$base    \$urgent    \$urgent
client.placeholder      \$overlay  \$base     \$text    \$overlay   \$overlay
EOF
echo "wrote i3/colors.conf"

# -------------------------------------------------------------------- tmux ---
cat > "$CFG/tmux/colors.conf" <<EOF
$GEN_HASH
# Minimal flat status line: no separators or blocks, the bar blends into the
# terminal background. Active window in purple, everything else muted.
# Single-line, minimal flat bar. (A terminal can't do fractional-height rows,
# so the bar is exactly one text row; there's no in-bar vertical padding.)
set -g status on
set -g status-style "bg=#$SURFACE,fg=#$SUBTEXT"
set -g status-justify left

set -g status-left-length 40
set -g status-left "#[fg=#$PURPLE,bold]  #S  #[fg=#$MUTED]│#[default]  "

set -g status-interval 2
set -g status-right-length 60
set -g status-right "#[fg=#$PINK]#(~/.config/tmux/git-branch.sh '#{pane_current_path}' '#{client_width}')#[default] "

set -g window-status-separator "   "
set -g window-status-format "#[fg=#$MUTED]#I #W#[default]"
set -g window-status-current-format "#[fg=#$PURPLE,bold]#I #W#[default]"

set -g pane-border-style "fg=#$OVERLAY"
set -g pane-active-border-style "fg=#$PURPLE"
set -g message-style "bg=#$SURFACE,fg=#$FG"
set -g mode-style "bg=#$PURPLE,fg=#$BG"
EOF
echo "wrote tmux/colors.conf"

# -------------------------------------------------------------------- nvim ---
mkdir -p "$CFG/nvim/lua/theme"
cat > "$CFG/nvim/lua/theme/palette.lua" <<EOF
-- $GEN
-- Fed to catppuccin's color_overrides.mocha (see lua/plugins/cat.lua).
return {
  rosewater = "#$PINK",
  flamingo  = "#$PINK",
  pink      = "#$PINK",
  mauve     = "#$PURPLE",
  red       = "#$RED",
  maroon    = "#$RED",
  peach     = "#$ORANGE",
  yellow    = "#$YELLOW",
  green     = "#$GREEN",
  teal      = "#$CYAN",
  sky       = "#$CYAN",
  sapphire  = "#$CYAN",
  blue      = "#$BLUE",
  lavender  = "#$PURPLE",
  text      = "#$FG",
  subtext1  = "#$SUBTEXT",
  subtext0  = "#$SUBTEXT",
  overlay2  = "#$MUTED",
  overlay1  = "#$MUTED",
  overlay0  = "#$OVERLAY",
  surface2  = "#$OVERLAY",
  surface1  = "#$SURFACE",
  surface0  = "#$SURFACE",
  base      = "#$BG",
  mantle    = "#$BG_DARK",
  crust     = "#$BG_DEEP",
}
EOF
echo "wrote nvim/lua/theme/palette.lua"

# ---------------------------------------------------------------- starship ---
# Starship has no include mechanism, so regenerate the [palettes.tokyonight]
# block in place, between the managed markers. Standard color names are
# overridden so existing "bold purple"/"bold blue" styles pick up the theme.
STAR="$CFG/starship/starship.toml"
if grep -q "theme palette >>>" "$STAR" 2>/dev/null; then
  awk -v P="$PURPLE" -v PK="$PINK" -v B="$BLUE" -v G="$GREEN" -v Y="$YELLOW" \
      -v R="$RED" -v C="$CYAN" -v FG="$FG" -v MU="$MUTED" '
    /# >>> theme palette >>>/ {
      print
      print "[palettes.tokyonight]"
      print "purple = \"#" P "\""
      print "pink   = \"#" PK "\""
      print "blue   = \"#" B "\""
      print "green  = \"#" G "\""
      print "yellow = \"#" Y "\""
      print "red    = \"#" R "\""
      print "cyan   = \"#" C "\""
      print "fg     = \"#" FG "\""
      print "muted  = \"#" MU "\""
      skip = 1; next
    }
    /# <<< theme palette <<</ { skip = 0; print; next }
    !skip { print }
  ' "$STAR" > "$STAR.tmp" && mv "$STAR.tmp" "$STAR"
  echo "wrote starship palette block"
fi

echo "done."
