return {
  'catppuccin/nvim',
  name = 'catppuccin',
  version = 'stable', -- pin: HEAD reads vim.o.pumborder which our nvim 0.12 nightly lacks (E5113)
  priority = 1000,
  opts = {
    flavour = 'mocha',
    -- Palette comes from the central theme (generated by ~/.config/theme/build.sh).
    color_overrides = { mocha = require('theme.palette') },
    -- Syntax highlighting: purple/pink lean but with variety; no harsh yellow.
    custom_highlights = function(c)
      local string_green = '#8fa876' -- deliberately dull/sage green for strings
      return {
        Comment                    = { fg = c.overlay1, italic = true },
        ['@comment']               = { fg = c.overlay1, italic = true },

        -- keywords -> purple, declarations/imports -> pink for variety
        ['@keyword']               = { fg = c.mauve },
        ['@keyword.function']      = { fg = c.pink },
        ['@keyword.return']        = { fg = c.mauve },
        ['@keyword.operator']      = { fg = c.mauve },
        ['@keyword.import']        = { fg = c.pink },
        ['@keyword.conditional']   = { fg = c.mauve },
        ['@keyword.repeat']        = { fg = c.mauve },
        ['@keyword.exception']     = { fg = c.mauve },
        ['@conditional']           = { fg = c.mauve },
        ['@repeat']                = { fg = c.mauve },

        -- functions -> blue, builtins -> cyan
        ['@function']              = { fg = c.blue },
        ['@function.call']         = { fg = c.blue },
        ['@function.method']       = { fg = c.blue },
        ['@function.builtin']      = { fg = c.sky },
        ['@function.macro']        = { fg = c.sky },
        ['@constructor']           = { fg = c.pink },

        -- types -> cyan (no more yellow/pink overload)
        ['@type']                  = { fg = c.sky },
        ['@type.builtin']          = { fg = c.sky },
        ['@type.definition']       = { fg = c.sky },

        -- strings -> dull green
        ['@string']                = { fg = string_green },
        ['@string.escape']         = { fg = c.pink },
        ['@string.regexp']         = { fg = c.peach },

        -- literals -> a touch of warm + pink
        ['@number']                = { fg = c.peach },
        ['@number.float']          = { fg = c.peach },
        ['@boolean']               = { fg = c.peach },
        ['@constant']              = { fg = c.pink },
        ['@constant.builtin']      = { fg = c.pink },

        -- identifiers
        ['@variable']              = { fg = c.text },
        ['@variable.builtin']      = { fg = c.red },  -- self / this
        ['@variable.parameter']    = { fg = c.text },
        ['@variable.member']       = { fg = c.blue }, -- fields / properties
        ['@property']              = { fg = c.blue },
        ['@field']                 = { fg = c.blue },
        ['@parameter']             = { fg = c.text },

        -- punctuation / operators -> muted
        ['@operator']              = { fg = c.subtext0 },
        ['@punctuation.bracket']   = { fg = c.overlay2 },
        ['@punctuation.delimiter'] = { fg = c.overlay2 },
        ['@punctuation.special']   = { fg = c.pink },

        -- markup / tags
        ['@tag']                   = { fg = c.mauve },
        ['@tag.attribute']         = { fg = c.sky },
        ['@tag.delimiter']         = { fg = c.overlay2 },
      }
    end,
  },
  config = function(_, opts)
    require('catppuccin').setup(opts)
    vim.cmd.colorscheme 'catppuccin'
  end,
}
